export const BankNames = [
    { id: 1, entitycode: "Axis Bank Ltd." },
    { id: 2, entitycode: "Bandhan Bank Ltd." },
    { id: 3, entitycode: "CSB Bank Ltd." },
    { id: 4, entitycode: "City Union Bank Ltd." },
    { id: 5, entitycode: "DCB Bank Ltd." },
    { id: 6, entitycode: "Dhanlaxmi Bank Ltd." },
    { id: 7, entitycode: "Federal Bank Ltd." },
    { id: 8, entitycode: "HDFC Bank Ltd." },
    { id: 9, entitycode: "ICICI Bank Ltd." },
    { id: 10, entitycode: "Induslnd Bank Ltd." },
    { id: 11, entitycode: "IDFC First Bank Ltd." },
    { id: 12, entitycode: "Jammu & Kashmir Bank Ltd." },
    { id: 13, entitycode: "Karnataka Bank Ltd." },
    { id: 14, entitycode: "Karur Vysya Bank Ltd." },
    { id: 15, entitycode: "Kotak Mahindra Bank Ltd." },
    { id: 16, entitycode: "Nainital Bank Ltd." },
    { id: 17, entitycode: "RBL Bank Ltd." },
    { id: 18, entitycode: "South Indian Bank Ltd." },
    { id: 19, entitycode: "Tamilnad Mercantile Bank Ltd." },
    { id: 20, entitycode: "YES Bank Ltd." },
    { id: 21, entitycode: "IDBI Bank Ltd." },
    { id: 22, entitycode: "Bank of Baroda" },
    { id: 23, entitycode: "Bank of India" },
    { id: 24, entitycode: "Bank of Maharashtra" },
    { id: 25, entitycode: "Canara Bank" },
    { id: 26, entitycode: "Central Bank of India" },
    { id: 27, entitycode: "Indian Bank" },
    { id: 28, entitycode: "Indian Overseas Bank" },
    { id: 29, entitycode: "Punjab & Sind Bank" },
    { id: 30, entitycode: "Punjab National Bank" },
    { id: 31, entitycode: "State Bank of India" },
    { id: 32, entitycode: "UCO Bank" },
    { id: 33, entitycode: "Union Bank of India" }
]
  